/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alertas`; params?: Router.UnknownInputParams; } | { pathname: `/notificaciones`; params?: Router.UnknownInputParams; } | { pathname: `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/../services/api`; params?: Router.UnknownInputParams; } | { pathname: `/../services/authservice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/professional-login` | `/professional-login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/select-patient` | `/select-patient`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/graficos` | `/graficos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/documentos` | `/documentos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/documentos/[id]` | `/documentos/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/alertas`; params?: Router.UnknownOutputParams; } | { pathname: `/notificaciones`; params?: Router.UnknownOutputParams; } | { pathname: `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/authservice`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/professional-login` | `/professional-login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/select-patient` | `/select-patient`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/graficos` | `/graficos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/documentos` | `/documentos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/documentos/[id]` | `/documentos/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/alertas${`?${string}` | `#${string}` | ''}` | `/notificaciones${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `/../services/api${`?${string}` | `#${string}` | ''}` | `/../services/authservice${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/professional-login${`?${string}` | `#${string}` | ''}` | `/professional-login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/select-patient${`?${string}` | `#${string}` | ''}` | `/select-patient${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/graficos${`?${string}` | `#${string}` | ''}` | `/graficos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/documentos${`?${string}` | `#${string}` | ''}` | `/documentos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alertas`; params?: Router.UnknownInputParams; } | { pathname: `/notificaciones`; params?: Router.UnknownInputParams; } | { pathname: `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/../services/api`; params?: Router.UnknownInputParams; } | { pathname: `/../services/authservice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/professional-login` | `/professional-login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/select-patient` | `/select-patient`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/graficos` | `/graficos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/documentos` | `/documentos`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/documentos/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/documentos/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tabs)'}/documentos/[id]` | `/documentos/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
